--TO VIEW THE TABLE


SELECT * FROM EMPLOYEES;                -- FOR ALL TABLE '*'
SELECT * FROM HR.EMPLOYEES;             -- 'HR' IS SCHEMA NAME\

SELECT FIRST_NAME,SALARY FROM EMPLOYEES;


--EXAMPLE 1 YEAR SALARY

SELECT SALARY,SALARY*12 FROM EMPLOYEES;


--EXAMPLE BONNUS SALARY (1 YEAR)

SELECT FIRST_NAME,(SALARY+500)*12 FROM EMPLOYEES;


--DESCRIBE TABLE

DESC EMPLOYEES;
DESCRIBE EMPLOYEES;


--SCHEME NAME

SELECT USER FROM DUAL;


--DUAL IS VIRTUAL TABLE

SELECT 100*5 FROM DUAL;
SELECT 'Peak Potensial' FROM DUAL;
SELECT 100+200,'Peak Potensial' FROM DUAL;

--ALIAS

SELECT FIRST_NAME AS NAME,SALARY "$$" FROM EMPLOYEES;

SELECT 100+5 AS ID FROM DUAL;
SELECT 'Peak Potensial' AS NAME FROM DUAL;

SELECT 100-5 "ID" FROM DUAL;
SELECT 'Peak Potensial' "NAME" FROM DUAL;

SELECT 100/5 AS COLUMN FROM DUAL;               --WRONG
SELECT 100+5 "COLUMN" FROM DUAL;                --CORRECT
--Since 'COLUMN' is a reserved keyword, it must be enclosed in quotation marks.



--Since there are 107 rows in 'EMPLOYEES', it will print that many.

SELECT 100*5 FROM EMPLOYEES;
SELECT 'Peak Potensial' FROM EMPLOYEES;


--Combine into one column

SELECT FIRST_NAME,LAST_NAME,SALARY FROM EMPLOYEES;
SELECT FIRST_NAME || LAST_NAME,SALARY FROM EMPLOYEES;
SELECT FIRST_NAME || ' ' || LAST_NAME AS NAME_SURNAME,SALARY FROM EMPLOYEES;
--If we take something with 2 or more words, we use underscores


--DISTINCT OR UNIQUE (UNIQUE ONLY IN ORACLE SQL)

SELECT DISTINCT LAST_NAME FROM EMPLOYEES;        --102 ROWS BECAUSE 5 ROWS ARE REPETITIVE
SELECT UNIQUE SALARY FROM EMPLOYEES;






